### ISSUE TITLE
UI not showing with new feature coming to Spotify

### ISSUE THREAD

**Issue by RyanTheTechMan** [timll/spotify-group-session#6]
A friend of mine is unable to see the group selection UI within the new device picker which some users are starting to see.

I manually tested this and it was true. I tested it by enabling the new device picker by checking "Enable showing a new and improved device picker UI" which is at the bottom of the Experimental Features list.

**Comment by t1mlange** [comment]
Hi Ryan,

I'm unable to opt in to experimental features [0], so I can't reproduce it myself. I assume the problem is that the CSS class name changed that I use to find the device menu in two locations [1, 2]. Maybe you want to tackle this? Use the developer options and right-click on the open device menu. Find the corresponding divs to [1] and [2] and replace the old names with the new ones.

- Tim 

[0] I'm using the Linux Flatpak version, but I've also read that not everyone can opt in to experimental features.
[1] https://github.com/timll/spotify-group-session/blob/main/src/group-session.js#L515
[2] https://github.com/timll/spotify-group-session/blob/main/src/group-session.js#L588

**Comment by RyanTheTechMan** [comment]
Hey,
In order to enable experimental features, run `spicetify config experimental_features 1`. You can find the options by clicking the profile button in the upper right of Spotify.

It looks like they obfuscated it :/

Blue is the device picker
Red is the list of devices

![image](https://user-images.githubusercontent.com/13668634/187096426-a418c082-429b-49fa-ab2c-347519851eb6.png)

To me, you could use the `aria-labelledby="device-picker-icon-button"` div to get into the list, but I'm not too sure if that's how you have been injecting.

**Comment by t1mlange** [comment]
> To me, you could use the `aria-labelledby="device-picker-icon-button"` div to get into the list, but I'm not too sure if that's how you have been injecting.

I can offer to look into this in 2 weeks.

**Comment by Moquent** [comment]
Hey! Spotify released their new update a while ago and it included the update of the new find devices UI which also broke the group session bar. Looking forward to have it back working!
![image](https://user-images.githubusercontent.com/63721912/189702606-c9de2321-bb85-4e02-9dc4-95eb9a2de10e.png)

**Comment by t1mlange** [comment]
I re-checked, but I don't see a "Enable showing a new and improved device picker UI" option in the experimental features. Did they rename it in the meantime?

**Comment by Moquent** [comment]
> I re-checked, but I don't see a "Enable showing a new and improved device picker UI" option in the experimental features. Did they rename it in the meantime?

they updated it directly, try the device picker in the updated version of Spotify. you don't have to enable the experimental feature for it, it's updated to the main Spotify branch
![image](https://user-images.githubusercontent.com/63721912/189924803-90a9341f-215a-46e0-880a-acac1587c603.png)
![image](https://user-images.githubusercontent.com/63721912/189924908-68c6fecd-6cb0-4ab2-bd46-a9d20535bbe2.png)
